salas-agendamento:
  request:
    mapping:
      salvar: /cliente
      listarClientes: /cliente
      findByCpf: /cliente/{cpf}
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9091/eureka/
    
spring:
  data.mongodb:
    host: localhost
    port: 27017
    database: sala-agendamento    
    
server:
  port: 8082    
