salas-agendamento:
  request:
    mapping:
      salvar: /cliente
      listarClientes: /cliente
      findByCpf: /cliente/{cpf}
      usuario: /usuario
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.100:9090/eureka/
    
spring:
  data.mongodb:
     uri: mongodb://mongo-cliente:27017/sala-agendamento-clientes
#    host: localhost
#    port: 27017
#    database: sala-agendamento-clientes
    
server:
  port: 8082    

logging:
  file: logs/cliente-log