salas-agendamento-horario:
  horarios:
    08:00,
    09:00,
    10:00,
    11:00,
    12:00,
    13:00,
    14:00,
    15:00,
    15:00,
    16:00,
    17:00,
    18:00,
    19:00,
    20:00

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9091/eureka/
    
server:
  port: 8083