salas-agendamento-sala:
  request:
    mapping:
      salas:
        findById: /sala/{id}
        listaSalasUnidade: /sala-unidades/{idUnidade}
        getSalas: /salas
        salvar: /sala

eureka:
  client:
    serviceUrl:
      #defaultZone: http://127.0.0.1:9090/eureka/
      defaultZone: http://192.168.0.100:9090/eureka/
        
spring:
  data.mongodb:
     uri: mongodb://localhost:27017/sala-agendamento-sala
     #uri: mongodb://mongo-sala:27017/sala-agendamento-sala
#    host: localhost
#    port: 27017
#    database: sala-agendamento-clientes
    
server:
  port: 8083

