salas-agendamento-agendamento:
  request:
    mapping:
      salvar: /agendamento
      listar: /agendamento
      listarFiltro: /agendamento/filtro
      listarFiltroDataESala: agendamento/filtro-data-sala
  horarios:
    08:00,
    09:00,
    10:00,
    11:00,
    12:00,
    13:00,
    14:00,
    15:00,
    15:00,
    16:00,
    17:00,
    18:00,
    19:00,
    20:00
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9091/eureka/
    
spring:
  data.mongodb:
    host: localhost
    port: 27017
    database: sala-agendamento    

server:
  port: 8081
