gateway:
  cliente-integration:
    url-user: http://192.168.0.20:8082/usuario

server:
  port: 9091
  
zuul:
  #Service will be mapped under the /api URI
  prefix: /api
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
  routes:
    ms-agendamento:
      path: /ms-agendamento/**
      serviceId: salas-agendamento-agenda
    ms-sala:
      path: /ms-sala/**
      serviceId: salas-agendamento-sala
    ms-cliente:
      path: /ms-cliente/**  
      serviceId: salas-agendamento-cliente
  ignored-headers:
  - Access-Control-Allow-Credentials
  - Access-Control-Allow-Origin

spring:
  redis:
#    host: 192.168.0.200       
#    port: 6379
    url: http://192.168.0.200:6379
      
eureka:
  client:
    serviceUrl:
#      defaultZone: http://192.168.0.100:9090/eureka/
#      defaultZone: http://127.0.0.1:9090/eureka/
      defaultZone: http://104.197.95.182:9090/eureka

logging:
  file: logs/gateway-log